const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const { initDb } = require('./db');
const { v4: uuidv4 } = require('uuid');

const app = express();
app.use(cors());
app.use(bodyParser.json());

const db = initDb();

function runQuery(sql, params=[]) {
  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) return reject(err);
      resolve(rows);
    });
  });
}

app.get('/api/forms', async (req, res) => {
  try {
    const rows = await runQuery('SELECT * FROM forms');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/forms', async (req, res) => {
  try {
    const id = uuidv4();
    const { title, description, active, assigned_course_id } = req.body;
    await runQuery('INSERT INTO forms (id, title, description, active, assigned_course_id) VALUES (?,?,?,?,?)', [id, title, description, active ? 1 : 0, assigned_course_id]);
    res.status(201).json({ id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/responses', async (req, res) => {
  try {
    const id = uuidv4();
    const { form_id, course_id, user_id, answers } = req.body;
    await runQuery('INSERT INTO responses (id, form_id, course_id, user_id) VALUES (?,?,?,?)', [id, form_id, course_id, user_id]);
    if (Array.isArray(answers)) {
      const insert = 'INSERT INTO answers (id, response_id, question_id, value) VALUES (?,?,?,?)';
      for (const a of answers) {
        await runQuery(insert, [uuidv4(), id, a.question_id, a.value]);
      }
    }
    res.status(201).json({ id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/responses', async (req, res) => {
  try {
    const rows = await runQuery('SELECT r.*, GROUP_CONCAT(a.value || "::" || a.question_id) as answers FROM responses r LEFT JOIN answers a ON a.response_id = r.id GROUP BY r.id ORDER BY submitted_at DESC');
    res.json(rows.map(r => ({ ...r, answers: r.answers ? r.answers.split(',').map(s => {
      const [value, question_id] = s.split('::');
      return { question_id, value };
    }) : [] })));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/dev/seed', async (req, res) => {
  try {
    const count = req.body.count || 100;
    // create a sample course, form, questions and random responses
    const courseId = uuidv4();
    await runQuery('INSERT OR IGNORE INTO courses (id, code, title) VALUES (?,?,?)', [courseId, 'C101', 'Demo Course']);
    const formId = uuidv4();
    await runQuery('INSERT OR IGNORE INTO forms (id, title, description, active, assigned_course_id) VALUES (?,?,?,?,?)', [formId, 'Demo Form', 'Autogenerated demo', 1, courseId]);
    // add 3 questions
    const q1 = uuidv4();
    const q2 = uuidv4();
    const q3 = uuidv4();
    await runQuery('INSERT OR IGNORE INTO questions (id, form_id, type, prompt, required, position) VALUES (?,?,?,?,?,?)', [q1, formId, 'scale', 'How would you rate the course?', 1, 1]);
    await runQuery('INSERT OR IGNORE INTO questions (id, form_id, type, prompt, required, position) VALUES (?,?,?,?,?,?)', [q2, formId, 'choice', 'Was the material clear?', 1, 2]);
    await runQuery('INSERT OR IGNORE INTO questions (id, form_id, type, prompt, required, position) VALUES (?,?,?,?,?,?)', [q3, formId, 'text', 'Any comments?', 0, 3]);
    for (let i=0;i<count;i++){
      const rid = uuidv4();
      await runQuery('INSERT INTO responses (id, form_id, course_id, user_id) VALUES (?,?,?,?)', [rid, formId, courseId, null]);
      const r1 = (Math.floor(Math.random()*5)+1).toString();
      const r2 = Math.random() > 0.5 ? 'yes' : 'no';
      const r3 = Math.random() > 0.7 ? 'Useful course' : '';
      await runQuery('INSERT INTO answers (id, response_id, question_id, value) VALUES (?,?,?,?)', [uuidv4(), rid, q1, r1]);
      await runQuery('INSERT INTO answers (id, response_id, question_id, value) VALUES (?,?,?,?)', [uuidv4(), rid, q2, r2]);
      await runQuery('INSERT INTO answers (id, response_id, question_id, value) VALUES (?,?,?,?)', [uuidv4(), rid, q3, r3]);
    }
    res.json({ seeded: count, courseId, formId });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log('Server listening on', PORT));
